name: Cache dqlite/liblxc dependencies
description: Restore dqlite/liblxc from the daily cache or build them

runs:
  using: composite
  steps:
    - name: deps cache key
      id: deps-cache-key
      shell: bash
      run: |
        set -eux
        . /etc/os-release
        ARCH="$(dpkg --print-architecture)"
        DATE="$(date --utc '+%Y%m%d')"
        YESTERDAY="$(date --utc '+%Y%m%d' --date=yesterday)"

        # i.e: deps-ubuntu-24.04-amd64-${DATE}
        echo "KEY=deps-${ID}-${VERSION_ID}-${ARCH}-${DATE}" >> $GITHUB_OUTPUT
        echo "FALLBACK_KEY=deps-${ID}-${VERSION_ID}-${ARCH}-${YESTERDAY}" >> $GITHUB_OUTPUT

    # GitHub will remove any cache entries that have not been accessed in over 7 days.
    # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
    - name: Cache dqlite/liblxc deps
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      id: cache-deps
      with:
        path: |
          /home/runner/go/bin/dqlite
          /home/runner/go/bin/liblxc
        key: ${{ steps.deps-cache-key.outputs.KEY }}
        restore-keys: |
          ${{ steps.deps-cache-key.outputs.FALLBACK_KEY }}

    - name: Build LXD dependencies
      if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        set -eux

        # Build from unpacked dist tarball.
        cd /home/runner/work/lxd/lxd-test
        make deps

        # Include dqlite libs in dependencies for system tests.
        mkdir -p /home/runner/go/bin/dqlite
        mv /home/runner/work/lxd/lxd-test/vendor/dqlite/include /home/runner/go/bin/dqlite/include
        mv /home/runner/work/lxd/lxd-test/vendor/dqlite/.libs /home/runner/go/bin/dqlite/libs

        # Include liblxc libs in dependencies for system tests.
        mkdir -p /home/runner/go/bin/liblxc
        mv /home/runner/work/lxd/lxd-test/vendor/liblxc/include /home/runner/go/bin/liblxc/include
        mv /home/runner/work/lxd/lxd-test/vendor/liblxc/lib /home/runner/go/bin/liblxc/libs

        # liblxc requires a rootfs dir
        mkdir -p /home/runner/go/bin/liblxc/rootfs
