#!/bin/bash
# report.sh
# Generates the CI failure report.
# The AI (GitHub Models) produces the full structured report using prompts/analyze.md.
# Edit prompts/analyze.md to change what the AI is asked and the expected output format.
# The model is selected via the REPRO_MODEL env var (set from the action's model input).
# Falls back to a minimal deterministic report when AI is unavailable.

set -e

echo "=== Generating report ===" >&2

meta_file="$REPRO_TMP/job.meta"
result_file="$REPRO_TMP/parse.result"
repro_result="$REPRO_TMP/reproducer.result"
context_file="$REPRO_TMP/code.context"
# The prompt file lives next to this script — edit it to change AI behaviour.
prompt_file="$(dirname "$0")/prompts/analyze.md"

# Model is configurable via action input (defaults to gpt-4o-mini).
model="${REPRO_MODEL:-gpt-4o-mini}"

# Source all result files.
set +e
[[ -f "$meta_file" ]] && source "$meta_file"
[[ -f "$result_file" ]] && source "$result_file"
[[ -f "$repro_result" ]] && source "$repro_result"
set -e

report=""

# ── Ask GitHub Models to produce the full structured report ──────────────────
# The system prompt (prompts/analyze.md) owns the expected output format.
# The user message is the raw failure context collected by the earlier steps.
# Requires models: read permission on the GITHUB_TOKEN.
if [[ -f "$prompt_file" ]] && [[ -n "$GITHUB_TOKEN" ]]; then
  echo "Requesting report from GitHub Models (model: $model)..." >&2

  system_prompt=$(cat "$prompt_file")

  # Build the user message: structured failure facts + code context.
  user_msg_file=$(mktemp)
  {
    echo "## Failure facts"
    echo ""
    echo "- Repository: ${GITHUB_REPOSITORY:-unknown}"
    echo "- Run ID: ${RUN_ID:-}"
    echo "- Run attempt: ${RUN_ATTEMPT:-1}"
    echo "- Actor: ${ACTOR:-}"
    echo "- Job: ${failed_job:-unknown}"
    echo "- Step: ${failed_step:-unknown}"
    echo "- Command: \`${failed_command:-unknown}\`"
    echo "- Error: ${error_message:-none}"
    echo "- Reproducer status: ${reproducer_status:-not-run}"
    echo "- Validation safe: ${validation_safe:-true}"
    echo ""
  } >> "$user_msg_file"

  if [[ -f "$context_file" ]]; then
    echo "" >> "$user_msg_file"
    echo "## Code evidence (source files, workflow YAML, log excerpts)" >> "$user_msg_file"
    echo "Use this to identify the exact location of the failure and produce a concrete fix." >> "$user_msg_file"
    echo "" >> "$user_msg_file"
    cat "$context_file" >> "$user_msg_file"
  fi

  ai_payload=$(jq -Rns \
    --arg system "$system_prompt" \
    --arg model "$model" \
    '{model:$model,
      messages:[{role:"system", content:$system},
                {role:"user",   content:.}],
      max_tokens:1200}' < "$user_msg_file")

  rm -f "$user_msg_file"

  ai_response=$(curl -s -f \
    -X POST "https://models.inference.ai.azure.com/chat/completions" \
    -H "Authorization: Bearer $GITHUB_TOKEN" \
    -H "Content-Type: application/json" \
    -d "$ai_payload" 2>/dev/null || true)

  report=$(echo "$ai_response" | jq -r '.choices[0].message.content // empty' 2>/dev/null || true)

  if [[ -n "$report" ]]; then
    echo "Report received from GitHub Models" >&2
    report="# CI Reproducer Report"$'\n\n'"_Generated by GitHub Models (${model})_"$'\n\n'"${report}"
  else
    echo "GitHub Models unavailable or returned no content; falling back to deterministic report" >&2
  fi
else
  [[ ! -f "$prompt_file" ]] && echo "WARNING: Prompt file not found at $prompt_file" >&2
  [[ -z "$GITHUB_TOKEN" ]] && echo "WARNING: GITHUB_TOKEN not set" >&2
fi

# ── Deterministic fallback ────────────────────────────────────────────────────
# Used only when the AI call is unavailable or returns nothing.
if [[ -z "$report" ]]; then
  echo "Using deterministic fallback report" >&2
  report="# CI Reproducer Report"$'\n\n'
  report+="> ⚠️ AI report unavailable. Add \`models: read\` permission to the ci-reproducer job and ensure \`GITHUB_TOKEN\` is set."$'\n\n'
  report+="## Summary"$'\n\n'
  report+="| Field | Value |"$'\n'
  report+="|-------|-------|"$'\n'
  report+="| Failed job | \`${failed_job:-unknown}\` |"$'\n'
  report+="| Failed step | \`${failed_step:-unknown}\` |"$'\n'
  report+="| Failed command | \`${failed_command:-unknown}\` |"$'\n'
  report+="| Key error | \`${error_message:0:150}\` |"$'\n'
  report+="| Confidence | ${confidence:-Low} |"$'\n\n'
  report+="## Reproducer"$'\n\n'
  if [[ -n "$failed_command" ]]; then
    report+="\`\`\`bash"$'\n'
    report+="# from repository root"$'\n'
    report+="$failed_command"$'\n'
    report+="\`\`\`"$'\n\n'
  fi
  report+="Reproduction: **not attempted**"$'\n\n'
  report+="## Notes"$'\n\n'
  report+="- Run ID: \`$RUN_ID\`, Attempt \`$RUN_ATTEMPT\`, Actor \`$ACTOR\`"$'\n'
fi

# ── Append code context as a collapsible section ─────────────────────────────
if [[ -f "$context_file" ]]; then
  report+=$'\n\n'
  report+="## Code Context"$'\n\n'
  report+="<details><summary>Source files and workflow step referenced in this failure</summary>"$'\n\n'
  report+=$(cat "$context_file")
  report+=$'\n\n'
  report+="</details>"
fi

# ── Write output ──────────────────────────────────────────────────────────────
if [[ -z "$GITHUB_STEP_SUMMARY" ]]; then
  echo "WARNING: GITHUB_STEP_SUMMARY not set; printing to stdout" >&2
  echo "$report"
else
  echo "$report" >> "$GITHUB_STEP_SUMMARY"
  echo "Report written to $GITHUB_STEP_SUMMARY" >&2
fi

if [[ -n "$GITHUB_OUTPUT" ]]; then
  {
    echo "report<<EOF"
    echo "$report"
    echo "EOF"
    echo "confidence=${confidence:-Low}"
    echo "reproducer-command=${reproducer_command:-}"
  } >> "$GITHUB_OUTPUT"
  echo "Outputs set in $GITHUB_OUTPUT" >&2
fi

echo "Report generation complete" >&2
