#!/bin/bash
# report.sh
# Generates the final Markdown report matching the specified format.
# Output: Writes to $GITHUB_STEP_SUMMARY and sets output variables

set -e

echo "=== Generating report ===" >&2

meta_file="$REPRO_TMP/job.meta"
result_file="$REPRO_TMP/parse.result"
repro_result="$REPRO_TMP/reproducer.result"
context_file="$REPRO_TMP/code.context"

# Source all result files
set +e
[[ -f "$meta_file" ]] && source "$meta_file"
[[ -f "$result_file" ]] && source "$result_file"
[[ -f "$repro_result" ]] && source "$repro_result"
set -e

# ── Ask GitHub Models (Copilot) for a concrete fix ───────────────────────────
# Requires models: read permission on the GITHUB_TOKEN.
# Gracefully skipped if unavailable.
ai_fix=""
if [[ -f "$context_file" ]] && [[ -n "$GITHUB_TOKEN" ]]; then
  echo "Requesting AI fix suggestion from GitHub Models..." >&2

  prompt_content=$(cat <<PROMPT
CI failure in repository ${GITHUB_REPOSITORY:-unknown}.

$(cat "$context_file")

Based on the above code context and error, provide:
1. **Root cause** (1-2 sentences, specific — reference exact file/line if available)
2. **Concrete fix** (show the exact code change or command needed, not generic advice)
PROMPT
)

  ai_payload=$(jq -n \
    --arg content "$prompt_content" \
    '{model:"gpt-4o-mini",
      messages:[{role:"system",content:"You are a CI failure analyst. Be direct and specific. Reference actual file names, line numbers, and code when available. Do not give generic advice."},
                {role:"user",content:$content}],
      max_tokens:700}')

  ai_response=$(curl -s -f \
    -X POST "https://models.inference.ai.azure.com/chat/completions" \
    -H "Authorization: Bearer $GITHUB_TOKEN" \
    -H "Content-Type: application/json" \
    -d "$ai_payload" 2>/dev/null || true)

  ai_fix=$(echo "$ai_response" | jq -r '.choices[0].message.content // empty' 2>/dev/null || true)

  if [[ -n "$ai_fix" ]]; then
    echo "AI fix suggestion obtained" >&2
  else
    echo "GitHub Models unavailable or returned no content; report will include raw code context" >&2
  fi
fi

# Build report
report=""

# === CI Reproducer Report Header ===
report+="# CI Reproducer Report"$'\n\n'

# === Summary Section ===
report+="## Summary"$'\n\n'

if [[ -n "$failed_job" ]]; then
  report+="- **Failed job:** \`$failed_job\`"$'\n'
elif [[ -n "$job_name" ]]; then
  report+="- **Failed job:** \`$job_name\`"$'\n'
fi

if [[ -n "$failed_step" ]]; then
  report+="- **Failed step:** \`$failed_step\`"$'\n'
fi

if [[ -n "$failed_command" ]]; then
  report+="- **Failed command:** \`${failed_command:0:160}\`"$'\n'
fi

if [[ -n "$error_message" ]]; then
  # Truncate long error messages
  truncated_error="${error_message:0:150}"
  [[ ${#error_message} -gt 150 ]] && truncated_error+="..."
  report+="- **Key error:** \`${truncated_error}\`"$'\n'
fi

if [[ -n "$likely_cause" ]]; then
  report+="- **Likely cause:** $likely_cause"$'\n'
elif [[ -n "$error_message" ]]; then
  report+="- **Likely cause:** Failure inferred from log evidence"$'\n'
fi

report+="- **Confidence:** $confidence"$'\n\n'

# === Reproducer Section ===
report+="## Reproducer"$'\n\n'
report+="Provide the smallest command a developer can run from the repository root:"$'\n\n'

if [[ -n "$reproducer_command" ]]; then
  report+="\`\`\`bash"$'\n'
  report+="# from repository root"$'\n'
  report+="$reproducer_command"$'\n'
  report+="\`\`\`"$'\n\n'
else
  report+="Unable to derive minimal reproducer command from available logs."$'\n\n'
fi

# Reproduction status
report+="Reproduction: "
if [[ "$reproducer_status" == "success" ]]; then
  report+="**not confirmed** (command ran but did not reproduce failure)"$'\n\n'
elif [[ "$reproducer_status" == "failed" ]]; then
  report+="**confirmed** (command reproduced failure with exit code $reproducer_exit_code)"$'\n\n'
elif [[ "$reproducer_status" == "timeout" ]]; then
  report+="**not confirmed** (reproducer timed out after $TIMEOUT_SECONDS seconds)"$'\n\n'
elif [[ "$reproducer_status" == "skipped" ]]; then
  report+="**not attempted** ($validation_reason)"$'\n\n'
elif [[ "$reproducer_status" == "not-run" ]]; then
  report+="**not attempted** (derived command was not safe to execute in CI reproducer)"$'\n\n'
else
  report+="**not attempted** (unable to derive command)"$'\n\n'
fi

# === Code Context Section ===
if [[ -f "$context_file" ]]; then
  report+="## Code Context"$'\n\n'
  report+="<details><summary>Source files and workflow step referenced in this failure</summary>"$'\n\n'
  report+=$(cat "$context_file")
  report+=$'\n\n'
  report+="</details>"$'\n\n'
fi

# === Potential Fix Section ===
report+="## Potential Fix"$'\n\n'

if [[ -n "$ai_fix" ]]; then
  # AI-generated fix from GitHub Models (Copilot)
  report+="_Generated by GitHub Models (gpt-4o-mini) from the code context above._"$'\n\n'
  report+="$ai_fix"$'\n\n'
else
  # Fallback: heuristic suggestions with raw evidence
  if [[ -n "$failed_command" ]]; then
    report+="Re-run the failing command locally to reproduce:"$'\n'
    report+="\`\`\`bash"$'\n'
    report+="$failed_command"$'\n'
    report+="\`\`\`"$'\n\n'
  fi
  if [[ -n "$error_message" ]]; then
    report+="**Error signal:** \`${error_message:0:200}\`"$'\n\n'
  fi
  if [[ -f "$context_file" ]]; then
    report+="Review the code context section above for the specific files and workflow step involved."$'\n\n'
  fi
  report+="_(Add \`models: read\` permission to the ci-reproducer job to enable AI-generated fix suggestions.)_"$'\n\n'
fi

# === Validation Section ===
report+="## Validation"$'\n\n'
report+="Commands actually executed:"$'\n\n'

if [[ "$reproducer_status" == "skipped" ]]; then
  report+="- Reproducer not executed (validation failure)"$'\n\n'
elif [[ "$reproducer_status" == "uncertain" ]] || [[ "$reproducer_status" == "not-run" ]]; then
  report+="- Unable to derive reproducer command"$'\n\n'
else
  report+="- \`${reproducer_command:0:100}\` → $reproducer_status"$'\n\n'

  # Show output snippet if available
  if [[ -n "$reproducer_stdout" ]] && [[ "$reproducer_stdout" != "\\n" ]]; then
    report+="**Last output:**"$'\n'
    report+="\`\`\`"$'\n'
    report+="${reproducer_stdout:0:500}"$'\n'
    report+="\`\`\`"$'\n\n'
  fi
fi

# === Notes Section ===
report+="## Notes"$'\n\n'

report+="- **Run context:** Run ID \`$RUN_ID\`, Attempt \`$RUN_ATTEMPT\`, Actor \`$ACTOR\`"$'\n'

if [[ "$confidence" == "Low" ]]; then
  report+="- **Confidence is Low:** The reproducer is uncertain. Test may be flaky or environment-dependent."$'\n'
fi

if [[ -n "$validation_reason" ]]; then
  report+="- **Validation note:** $validation_reason"$'\n'
fi

if [[ "$reproducer_exit_code" -eq 0 ]] && [[ "$reproducer_status" != "skipped" ]]; then
  report+="- **No failure reproduced:** The minimal command succeeded, but CI failed. This suggests:"$'\n'
  report+="  - Test is flaky or timing-dependent"$'\n'
  report+="  - Environment differs between CI and local setup"$'\n'
  report+="  - Reproduction command is incomplete"$'\n'
fi

report+="- **How to use:** Copy the reproducer command and run from repository root. Adjust as needed for local environment."$'\n\n'

# Write to $GITHUB_STEP_SUMMARY
if [[ -z "$GITHUB_STEP_SUMMARY" ]]; then
  echo "WARNING: GITHUB_STEP_SUMMARY not set. Output to stdout instead." >&2
  echo "$report"
else
  echo "$report" >> "$GITHUB_STEP_SUMMARY"
  echo "Report written to $GITHUB_STEP_SUMMARY" >&2
fi

# Set GitHub Actions outputs
if [[ -n "$GITHUB_OUTPUT" ]]; then
  {
    echo "report<<EOF"
    echo "$report"
    echo "EOF"
    echo "confidence=$confidence"
    echo "reproducer-command=$reproducer_command"
  } >> "$GITHUB_OUTPUT"
  echo "Outputs set in $GITHUB_OUTPUT" >&2
fi

echo "Report generation complete" >&2
