name: Tests
on:
  - push
  - pull_request

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-tests:
    env:
      CGO_CFLAGS: "-I/home/runner/work/lxd/lxd-test/vendor/raft/include/ -I/home/runner/work/lxd/lxd-test/vendor/dqlite/include/"
      CGO_LDFLAGS: "-L/home/runner/work/lxd/lxd-test/vendor/raft/.libs -L/home/runner/work/lxd/lxd-test/vendor/dqlite/.libs/"
      LD_LIBRARY_PATH: "/home/runner/work/lxd/lxd-test/vendor/raft/.libs/:/home/runner/work/lxd/lxd-test/vendor/dqlite/.libs/"
      CGO_LDFLAGS_ALLOW: "(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"
    name: Code tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        if: github.event_name == 'pull_request'

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18.x

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-lxc/lxc-git-master -y --no-update
          sudo apt-get update

          sudo apt-get install --no-install-recommends -y \
            curl \
            gettext \
            git \
            libacl1-dev \
            libcap-dev \
            libdbus-1-dev \
            liblxc-dev \
            lxc-templates \
            libseccomp-dev \
            libselinux-dev \
            libsqlite3-dev \
            libdqlite0 \
            libtool \
            libudev-dev \
            libuv1-dev \
            make \
            pkg-config \
            shellcheck \
            build-essential \

          python3 -m pip install flake8

      - name: Download go dependencies
        run: |
          go mod download

      - name: Make LXD tarball and unpack it
        env:
          CUSTOM_VERSION: "test"
        run: |
          make dist
          tar -xzf lxd-test.tar.gz -C ~/work/lxd/
          rm lxd-test.tar.gz

      - name: Build LXD dependencies
        run: |
          cd ~/work/lxd/lxd-test
          make deps

      - name: Run LXD build
        run: |
          make
      
      - name: Debugging
        run: |
          ls -l /home/runner/work/lxd/lxd-test/vendor/dqlite/.libs/
          echo $LD_LIBRARY_PATH
          sudo ldconfig -v

      - name: Unit tests (all)
        run: |
          pwd
          sudo --preserve-env=PATH,GOPATH,CGO_CFLAGS,CGO_LDFLAGS,CGO_LDFLAGS_ALLOW,LD_LIBRARY_PATH go test ./...
          
      - name: Run static analysis
        run: |
          make static-analysis
